apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeployment
  namespace: test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webpod
      labels: 
        app: webapp
    spec: 
      containers:
      - name: webcontainer
        image: kkeducation12345/spring-app:1.0.3
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "600m"
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata:
  name: webservice
  namespace: test
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 8080
